[build]
  command = "next build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.12.2"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["pg"]

[[plugins]]
  package = "netlify-plugin-cache-nextjs"
